development:
  bucket: download.forumdg.com
  access_key_id: AKIAJBCD7DNSI4HEQIVQ
  secret_access_key: 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

test:
  bucket: download.forumdg.com
  access_key_id: AKIAJBCD7DNSI4HEQIVQ
  secret_access_key: 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

production:
  bucket: download.forumdg.com
  access_key_id: AKIAJBCD7DNSI4HEQIVQ
  secret_access_key: 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
